### ISSUE TITLE
Gaia query does not return all targets

### ISSUE THREAD

**Issue by christinahedges** [jorgemarpa/psfmachine#2]
I'm testing out `psfmachine`, and have come across the following issue. It looks like Gaia is not identifying all the targets in TPFs. This is a test of the 100 TPFs around K2-18. 

![test](https://user-images.githubusercontent.com/14965634/103709349-36876200-4f67-11eb-8111-6df5443799ba.png)

You can see lots of TPFs aren't highlighted. I set a pretty tolerant magnitude limit (down to 20th magnitude) and they still aren't being found. This -could- be a bandpass problem, but I'm not sure. It seems like we might have to rely on both Gaia (for source positions and source identification) and the original mission input catalogs (for additional source identification) . This creates a bit of a nasty crossmatch problem.

**Comment by christinahedges** [comment]
It looks like it might be line 50 in the gaia query:

This
```python
        rads.append(np.hypot(ra1 - ra1.mean(), dec1 - dec1.mean()).max()/2 + (u.arcsecond * 6).to(u.deg).value)
```

should be 
```python
        rads.append(np.hypot(ra1 - ra1.mean(), dec1 - dec1.mean()).max() + (u.arcsecond * 6).to(u.deg).value)
```

**Comment by jorgemarpa** [comment]
When reproducing this issue, I found that the WCS conversion done by `psfmachine` was buggy, it was doing a wrong projection of TPFs to RaDec coordinates for a group of TPF, which lead to the wrong Gaia query inputs (coord, radius).

This figure shows the correct coordinates for the same collection of TPFs and the Gaia sources:
![download-2](https://user-images.githubusercontent.com/10449555/104391975-f2abd400-54f5-11eb-98d8-06267302c2b1.png)
